### ISSUE TITLE
Open Discussion for Initial Roadmap of Matcheos (All Welcome)

### ISSUE THREAD

**Issue by crypto5000** [crypto5000/matcheos#1]
## Guidelines
If you'd like to comment or contribute to any area of Matcheos, please post below. The current areas that seem the most modular for subdivision are:

1. Profiles - Creating the user profiles that other people see. Most likely people will bid directly on the profile page.
2. Matching - Working on the algorithm to match bids.
3. Meeting - Working on the smart contract and multi-sig wallet to release the tokens.
4. Community - Handling marketing tasks to increase the uptake of profiles and builds.
5. DevOps - Implementing the tooling/testing/deploying of Matcheos.

**Comment by ChrisChiasson** [comment]
I am interested in helping, specifically on anything related to storage. Like how to host larger profile data like pictures.

**Comment by ChrisChiasson** [comment]
Right now it seems like that data is on the web. Hrm. So I guess only the logic can be eos right now. Still, this is the kind of application that could be useful, so if you have a suggested task for someone that knows C++ and wants to get into EOS, let me know. (I am a mechanical engineer, but I want to do EOS apps on the weekends.)

**Comment by ChrisChiasson** [comment]
Btw have you looked at swarm and livepeer?
